/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TRANSIT_REALTIME_GTFS_REALTIME_PB_H_INCLUDED
#define PB_TRANSIT_REALTIME_GTFS_REALTIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _transit_realtime_FeedHeader {
    char dummy_field;
} transit_realtime_FeedHeader;

typedef struct _transit_realtime_FeedMessage {
    transit_realtime_FeedHeader header;
    pb_callback_t entity;
} transit_realtime_FeedMessage;

typedef struct _transit_realtime_TripUpdate_StopTimeEvent {
    bool has_time;
    int64_t time;
} transit_realtime_TripUpdate_StopTimeEvent;

typedef struct _transit_realtime_TripUpdate_StopTimeUpdate {
    bool has_arrival;
    transit_realtime_TripUpdate_StopTimeEvent arrival;
    bool has_departure;
    transit_realtime_TripUpdate_StopTimeEvent departure;
    pb_callback_t stop_id;
} transit_realtime_TripUpdate_StopTimeUpdate;

typedef struct _transit_realtime_TripDescriptor {
    pb_callback_t route_id;
} transit_realtime_TripDescriptor;

typedef struct _transit_realtime_TripUpdate {
    transit_realtime_TripDescriptor trip;
    pb_callback_t stop_time_update;
} transit_realtime_TripUpdate;

typedef struct _transit_realtime_FeedEntity {
    bool has_trip_update;
    transit_realtime_TripUpdate trip_update;
} transit_realtime_FeedEntity;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define transit_realtime_FeedMessage_init_default {transit_realtime_FeedHeader_init_default, {{NULL}, NULL}}
#define transit_realtime_FeedHeader_init_default {0}
#define transit_realtime_FeedEntity_init_default {false, transit_realtime_TripUpdate_init_default}
#define transit_realtime_TripUpdate_init_default {transit_realtime_TripDescriptor_init_default, {{NULL}, NULL}}
#define transit_realtime_TripUpdate_StopTimeEvent_init_default {false, 0}
#define transit_realtime_TripUpdate_StopTimeUpdate_init_default {false, transit_realtime_TripUpdate_StopTimeEvent_init_default, false, transit_realtime_TripUpdate_StopTimeEvent_init_default, {{NULL}, NULL}}
#define transit_realtime_TripDescriptor_init_default {{{NULL}, NULL}}
#define transit_realtime_FeedMessage_init_zero   {transit_realtime_FeedHeader_init_zero, {{NULL}, NULL}}
#define transit_realtime_FeedHeader_init_zero    {0}
#define transit_realtime_FeedEntity_init_zero    {false, transit_realtime_TripUpdate_init_zero}
#define transit_realtime_TripUpdate_init_zero    {transit_realtime_TripDescriptor_init_zero, {{NULL}, NULL}}
#define transit_realtime_TripUpdate_StopTimeEvent_init_zero {false, 0}
#define transit_realtime_TripUpdate_StopTimeUpdate_init_zero {false, transit_realtime_TripUpdate_StopTimeEvent_init_zero, false, transit_realtime_TripUpdate_StopTimeEvent_init_zero, {{NULL}, NULL}}
#define transit_realtime_TripDescriptor_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define transit_realtime_FeedMessage_header_tag  1
#define transit_realtime_FeedMessage_entity_tag  2
#define transit_realtime_TripUpdate_StopTimeEvent_time_tag 2
#define transit_realtime_TripUpdate_StopTimeUpdate_arrival_tag 2
#define transit_realtime_TripUpdate_StopTimeUpdate_departure_tag 3
#define transit_realtime_TripUpdate_StopTimeUpdate_stop_id_tag 4
#define transit_realtime_TripDescriptor_route_id_tag 5
#define transit_realtime_TripUpdate_trip_tag     1
#define transit_realtime_TripUpdate_stop_time_update_tag 2
#define transit_realtime_FeedEntity_trip_update_tag 3

/* Struct field encoding specification for nanopb */
#define transit_realtime_FeedMessage_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  header,            1) \
X(a, CALLBACK, REPEATED, MESSAGE,  entity,            2)
#define transit_realtime_FeedMessage_CALLBACK pb_default_field_callback
#define transit_realtime_FeedMessage_DEFAULT NULL
#define transit_realtime_FeedMessage_header_MSGTYPE transit_realtime_FeedHeader
#define transit_realtime_FeedMessage_entity_MSGTYPE transit_realtime_FeedEntity

#define transit_realtime_FeedHeader_FIELDLIST(X, a) \

#define transit_realtime_FeedHeader_CALLBACK NULL
#define transit_realtime_FeedHeader_DEFAULT NULL

#define transit_realtime_FeedEntity_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trip_update,       3)
#define transit_realtime_FeedEntity_CALLBACK NULL
#define transit_realtime_FeedEntity_DEFAULT NULL
#define transit_realtime_FeedEntity_trip_update_MSGTYPE transit_realtime_TripUpdate

#define transit_realtime_TripUpdate_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  trip,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  stop_time_update,   2)
#define transit_realtime_TripUpdate_CALLBACK pb_default_field_callback
#define transit_realtime_TripUpdate_DEFAULT NULL
#define transit_realtime_TripUpdate_trip_MSGTYPE transit_realtime_TripDescriptor
#define transit_realtime_TripUpdate_stop_time_update_MSGTYPE transit_realtime_TripUpdate_StopTimeUpdate

#define transit_realtime_TripUpdate_StopTimeEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT64,    time,              2)
#define transit_realtime_TripUpdate_StopTimeEvent_CALLBACK NULL
#define transit_realtime_TripUpdate_StopTimeEvent_DEFAULT NULL

#define transit_realtime_TripUpdate_StopTimeUpdate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  arrival,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  departure,         3) \
X(a, CALLBACK, OPTIONAL, STRING,   stop_id,           4)
#define transit_realtime_TripUpdate_StopTimeUpdate_CALLBACK pb_default_field_callback
#define transit_realtime_TripUpdate_StopTimeUpdate_DEFAULT NULL
#define transit_realtime_TripUpdate_StopTimeUpdate_arrival_MSGTYPE transit_realtime_TripUpdate_StopTimeEvent
#define transit_realtime_TripUpdate_StopTimeUpdate_departure_MSGTYPE transit_realtime_TripUpdate_StopTimeEvent

#define transit_realtime_TripDescriptor_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   route_id,          5)
#define transit_realtime_TripDescriptor_CALLBACK pb_default_field_callback
#define transit_realtime_TripDescriptor_DEFAULT NULL

extern const pb_msgdesc_t transit_realtime_FeedMessage_msg;
extern const pb_msgdesc_t transit_realtime_FeedHeader_msg;
extern const pb_msgdesc_t transit_realtime_FeedEntity_msg;
extern const pb_msgdesc_t transit_realtime_TripUpdate_msg;
extern const pb_msgdesc_t transit_realtime_TripUpdate_StopTimeEvent_msg;
extern const pb_msgdesc_t transit_realtime_TripUpdate_StopTimeUpdate_msg;
extern const pb_msgdesc_t transit_realtime_TripDescriptor_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define transit_realtime_FeedMessage_fields &transit_realtime_FeedMessage_msg
#define transit_realtime_FeedHeader_fields &transit_realtime_FeedHeader_msg
#define transit_realtime_FeedEntity_fields &transit_realtime_FeedEntity_msg
#define transit_realtime_TripUpdate_fields &transit_realtime_TripUpdate_msg
#define transit_realtime_TripUpdate_StopTimeEvent_fields &transit_realtime_TripUpdate_StopTimeEvent_msg
#define transit_realtime_TripUpdate_StopTimeUpdate_fields &transit_realtime_TripUpdate_StopTimeUpdate_msg
#define transit_realtime_TripDescriptor_fields &transit_realtime_TripDescriptor_msg

/* Maximum encoded size of messages (where known) */
/* transit_realtime_FeedMessage_size depends on runtime parameters */
/* transit_realtime_FeedEntity_size depends on runtime parameters */
/* transit_realtime_TripUpdate_size depends on runtime parameters */
/* transit_realtime_TripUpdate_StopTimeUpdate_size depends on runtime parameters */
/* transit_realtime_TripDescriptor_size depends on runtime parameters */
#define TRANSIT_REALTIME_GTFS_REALTIME_PB_H_MAX_SIZE transit_realtime_TripUpdate_StopTimeEvent_size
#define transit_realtime_FeedHeader_size         0
#define transit_realtime_TripUpdate_StopTimeEvent_size 11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
